global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mds_rpc_metrics'
    metrics_path: /rpc.MdsService/GetMetricsProm
    static_configs:
      - targets: ['222.20.95.30:8010']
        labels: { instance: 'mds-server' }

  - job_name: 'storage_rpc_metrics'
    metrics_path: /rpc.StorageService/GetMetricsProm
    static_configs:
      - targets: ['222.20.95.30:8011']
        labels: { instance: 'storage-server' }

  - job_name: 'vfs_rpc_metrics'
    metrics_path: /rpc.VfsService/GetMetricsProm
    static_configs:
      - targets: ['222.20.95.30:8012']
        labels: { instance: 'vfs-server' }